site_name: LaPaillasse 
plugins:
    - drawio
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight

theme : 
  name : dracula
  icon:
    annotation: material/arrow-right-circle
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
