site_name: LaPaillasse 
markdown_extensions:
  - pymdownx.emoji:
      emoji_generator: 
        python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed
  - attr_list
  - md_in_html
  - pymdownx.superfences

theme : 
  name : material
  icon:
    annotation: material/arrow-right-circle
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
